// Leadership Assessment Statements Database
// 200 statements covering all 6 Goleman leadership styles
// Tailored for Pakistani pharmaceutical industry context

const LEADERSHIP_STATEMENTS = [
    // Coercive Style (33 statements)
    { id: 1, text: "When launching a new pharmaceutical product in Pakistan, I prefer to give direct orders to my sales team rather than seeking their input on market strategy.", style: "coercive" },
    { id: 2, text: "During territory planning meetings, I make all the key decisions about doctor coverage and product positioning without consulting my team members.", style: "coercive" },
    { id: 3, text: "When a medical representative fails to meet their monthly prescription targets, I immediately implement strict monitoring and corrective measures.", style: "coercive" },
    { id: 4, text: "I believe that in the competitive Pakistani pharma market, team members perform best when they follow my instructions exactly without questioning.", style: "coercive" },
    { id: 5, text: "When dealing with regulatory compliance issues, I prefer to dictate the exact procedures my team must follow rather than allowing flexibility.", style: "coercive" },
    { id: 6, text: "During product training sessions, I expect my team to implement my teaching methods precisely without adapting them to their own style.", style: "coercive" },
    { id: 7, text: "When managing relationships with key opinion leaders in Pakistan's medical community, I control all communication and don't delegate this responsibility.", style: "coercive" },
    { id: 8, text: "I find it most effective to use my authority to ensure immediate compliance when team members resist new pharmaceutical marketing strategies.", style: "coercive" },
    { id: 9, text: "When organizing medical conferences or CME events, I make all decisions about speakers, venues, and content without team input.", style: "coercive" },
    { id: 10, text: "I believe that clear hierarchical structure is essential in pharmaceutical sales, and team members should not question my directives.", style: "coercive" },
    { id: 11, text: "When handling customer complaints about our pharmaceutical products, I prefer to personally manage all responses rather than empowering my team.", style: "coercive" },
    { id: 12, text: "During budget planning for promotional activities, I make all allocation decisions without seeking input from field representatives.", style: "coercive" },
    { id: 13, text: "When implementing new CRM systems or digital tools, I require strict adherence to my prescribed usage methods.", style: "coercive" },
    { id: 14, text: "I use my position to ensure that team members follow company policies exactly, even when they suggest more efficient alternatives.", style: "coercive" },
    { id: 15, text: "When negotiating with hospital procurement committees, I prefer to handle all discussions personally rather than training my team.", style: "coercive" },
    { id: 16, text: "During performance reviews, I focus primarily on compliance with my instructions rather than encouraging creative problem-solving.", style: "coercive" },
    { id: 17, text: "When launching promotional campaigns for generic medicines, I require my team to follow my marketing approach without modification.", style: "coercive" },
    { id: 18, text: "I believe that in crisis situations, such as product recalls or adverse events, immediate obedience to my commands is more important than discussion.", style: "coercive" },
    { id: 19, text: "When managing relationships with pharmacy chains across Pakistan, I personally control all negotiations and pricing discussions.", style: "coercive" },
    { id: 20, text: "During team meetings, I prefer to announce decisions rather than facilitate discussions about pharmaceutical market challenges.", style: "coercive" },
    { id: 21, text: "When training new medical representatives, I require them to use my exact presentation style and materials without personalization.", style: "coercive" },
    { id: 22, text: "I find it necessary to closely monitor my team's daily activities and require detailed reports on all doctor visits.", style: "coercive" },
    { id: 23, text: "When dealing with competitive pressures in the Pakistani pharmaceutical market, I make strategic decisions unilaterally.", style: "coercive" },
    { id: 24, text: "During product positioning discussions, I prefer to dictate the key messages rather than collaborating with my team on messaging strategy.", style: "coercive" },
    { id: 25, text: "When managing inventory and stock levels across territories, I make all distribution decisions without consulting field teams.", style: "coercive" },
    { id: 26, text: "I believe that maintaining strict control over promotional budgets and expenses is more important than giving teams financial autonomy.", style: "coercive" },
    { id: 27, text: "When addressing ethical concerns in pharmaceutical marketing, I prefer to issue clear directives rather than engaging in team discussions.", style: "coercive" },
    { id: 28, text: "During territory restructuring, I make all assignment decisions based on my assessment without seeking team member preferences.", style: "coercive" },
    { id: 29, text: "When implementing new sales processes or methodologies, I require exact replication of my prescribed approach.", style: "coercive" },
    { id: 30, text: "I find it most effective to use formal authority to resolve conflicts between team members rather than facilitating collaborative solutions.", style: "coercive" },
    { id: 31, text: "When managing key account relationships with major hospitals, I prefer to maintain personal control rather than delegating to team members.", style: "coercive" },
    { id: 32, text: "During market research activities, I direct my team on exactly what information to collect and how to analyze it.", style: "coercive" },
    { id: 33, text: "When facing regulatory inspections or audits, I require my team to follow my specific protocols without deviation or discussion.", style: "coercive" },

    // Authoritative Style (33 statements)
    { id: 34, text: "I inspire my pharmaceutical sales team by painting a clear vision of how our products can improve patient outcomes across Pakistan.", style: "authoritative" },
    { id: 35, text: "When launching new therapeutic solutions, I help my team understand how their work contributes to advancing healthcare in Pakistani communities.", style: "authoritative" },
    { id: 36, text: "I motivate medical representatives by connecting their daily doctor visits to our larger mission of providing accessible healthcare solutions.", style: "authoritative" },
    { id: 37, text: "During challenging market conditions, I rally my team around our shared commitment to bringing innovative medicines to Pakistani patients.", style: "authoritative" },
    { id: 38, text: "I create enthusiasm for new product launches by helping my team visualize the positive impact on treatment outcomes in our target markets.", style: "authoritative" },
    { id: 39, text: "When setting annual targets, I inspire my team by explaining how achieving these goals advances our company's healthcare mission in Pakistan.", style: "authoritative" },
    { id: 40, text: "I encourage my team to see beyond sales numbers and understand their role in improving the quality of life for patients across the country.", style: "authoritative" },
    { id: 41, text: "During team meetings, I share compelling stories about how our pharmaceutical products have made a difference in patients' lives.", style: "authoritative" },
    { id: 42, text: "I help my team understand how our work in the Pakistani pharmaceutical market contributes to global health initiatives and medical advancement.", style: "authoritative" },
    { id: 43, text: "When facing competitive challenges, I inspire confidence by reminding my team of our unique value proposition and therapeutic advantages.", style: "authoritative" },
    { id: 44, text: "I motivate my team by articulating a clear vision of how we can become the leading pharmaceutical company in our therapeutic areas.", style: "authoritative" },
    { id: 45, text: "During product training sessions, I inspire learning by connecting clinical knowledge to real-world patient benefits and treatment success stories.", style: "authoritative" },
    { id: 46, text: "I encourage my team to embrace new digital marketing tools by showing how these innovations can enhance our reach to healthcare providers.", style: "authoritative" },
    { id: 47, text: "When implementing new strategies, I inspire buy-in by clearly communicating the long-term benefits for both our team and Pakistani healthcare.", style: "authoritative" },
    { id: 48, text: "I motivate medical representatives by helping them understand how building strong doctor relationships contributes to better patient care.", style: "authoritative" },
    { id: 49, text: "During challenging periods, I maintain team morale by reinforcing our shared purpose of making quality medicines accessible to all Pakistanis.", style: "authoritative" },
    { id: 50, text: "I inspire innovation in my team by encouraging them to think creatively about how to overcome healthcare access barriers in rural Pakistan.", style: "authoritative" },
    { id: 51, text: "When setting team goals, I connect individual performance targets to our broader mission of improving healthcare outcomes nationwide.", style: "authoritative" },
    { id: 52, text: "I encourage my team to take pride in their work by highlighting how pharmaceutical sales contributes to medical progress and patient welfare.", style: "authoritative" },
    { id: 53, text: "During market expansion initiatives, I inspire my team with a compelling vision of reaching underserved communities with essential medicines.", style: "authoritative" },
    { id: 54, text: "I motivate my team by sharing success stories of how our collaborative efforts have led to improved treatment protocols in Pakistani hospitals.", style: "authoritative" },
    { id: 55, text: "When introducing new therapeutic areas, I inspire enthusiasm by explaining the unmet medical needs we can address in the Pakistani market.", style: "authoritative" },
    { id: 56, text: "I encourage my team to see themselves as healthcare partners rather than just sales representatives, emphasizing their role in patient care.", style: "authoritative" },
    { id: 57, text: "During strategic planning sessions, I inspire my team with a clear vision of how we can lead innovation in Pakistan's pharmaceutical industry.", style: "authoritative" },
    { id: 58, text: "I motivate my team by connecting their professional development to our company's growth and leadership in the Pakistani healthcare sector.", style: "authoritative" },
    { id: 59, text: "When facing regulatory changes, I inspire confidence by explaining how compliance excellence positions us as a trusted healthcare partner.", style: "authoritative" },
    { id: 60, text: "I encourage my team to embrace continuous learning by showing how medical knowledge directly translates to better patient outcomes.", style: "authoritative" },
    { id: 61, text: "During territory planning, I inspire my team with a vision of comprehensive healthcare coverage and improved access to essential medicines.", style: "authoritative" },
    { id: 62, text: "I motivate medical representatives by helping them understand how their expertise contributes to evidence-based prescribing practices.", style: "authoritative" },
    { id: 63, text: "When launching patient assistance programs, I inspire my team with our mission to make life-saving treatments affordable for all Pakistanis.", style: "authoritative" },
    { id: 64, text: "I encourage my team to think beyond traditional sales approaches by envisioning innovative ways to support healthcare providers and patients.", style: "authoritative" },
    { id: 65, text: "During performance discussions, I inspire improvement by connecting individual growth to our collective impact on Pakistani healthcare advancement.", style: "authoritative" },
    { id: 66, text: "I motivate my team by articulating how our success in the pharmaceutical market contributes to Pakistan's overall health and economic development.", style: "authoritative" },

    // Affiliative Style (33 statements)
    { id: 67, text: "I prioritize building strong personal relationships with my pharmaceutical sales team members, understanding their individual challenges and aspirations.", style: "affiliative" },
    { id: 68, text: "When team members face personal difficulties that affect their performance, I offer flexible support and understanding rather than strict enforcement.", style: "affiliative" },
    { id: 69, text: "I create a warm, family-like atmosphere in our pharmaceutical team where everyone feels valued and emotionally supported.", style: "affiliative" },
    { id: 70, text: "During team conflicts, I focus on healing relationships and restoring harmony rather than immediately addressing performance issues.", style: "affiliative" },
    { id: 71, text: "I regularly check in with my medical representatives about their well-being and work-life balance, not just their sales numbers.", style: "affiliative" },
    { id: 72, text: "When celebrating achievements, I emphasize team unity and collective success rather than individual accomplishments in pharmaceutical sales.", style: "affiliative" },
    { id: 73, text: "I encourage open communication and emotional expression during team meetings, creating a safe space for sharing concerns and ideas.", style: "affiliative" },
    { id: 74, text: "When team members make mistakes in their pharmaceutical marketing activities, I focus on learning and support rather than criticism.", style: "affiliative" },
    { id: 75, text: "I invest significant time in understanding each team member's personal motivations and career aspirations in the pharmaceutical industry.", style: "affiliative" },
    { id: 76, text: "During stressful periods like product launches or regulatory changes, I prioritize maintaining team morale and emotional well-being.", style: "affiliative" },
    { id: 77, text: "I organize team-building activities and social events to strengthen bonds between pharmaceutical sales team members.", style: "affiliative" },
    { id: 78, text: "When making decisions about territory assignments or role changes, I consider the personal preferences and family situations of team members.", style: "affiliative" },
    { id: 79, text: "I create an environment where team members feel comfortable sharing personal challenges that might impact their pharmaceutical sales performance.", style: "affiliative" },
    { id: 80, text: "During performance reviews, I emphasize positive feedback and personal growth rather than focusing primarily on areas for improvement.", style: "affiliative" },
    { id: 81, text: "I encourage collaboration and mutual support among medical representatives, fostering a sense of shared responsibility for team success.", style: "affiliative" },
    { id: 82, text: "When team members disagree on pharmaceutical marketing strategies, I facilitate discussions that preserve relationships while finding solutions.", style: "affiliative" },
    { id: 83, text: "I show genuine interest in my team members' families and personal lives, remembering important events and milestones.", style: "affiliative" },
    { id: 84, text: "During challenging market conditions, I focus on maintaining team cohesion and mutual support rather than increasing pressure for results.", style: "affiliative" },
    { id: 85, text: "I create opportunities for team members to support each other's professional development and share knowledge about pharmaceutical products.", style: "affiliative" },
    { id: 86, text: "When addressing performance issues, I approach conversations with empathy and focus on understanding underlying personal or professional challenges.", style: "affiliative" },
    { id: 87, text: "I prioritize creating a positive work environment where pharmaceutical sales team members enjoy coming to work and feel appreciated.", style: "affiliative" },
    { id: 88, text: "During team meetings, I ensure everyone has a voice and feels heard, even when discussing technical pharmaceutical or regulatory topics.", style: "affiliative" },
    { id: 89, text: "I celebrate personal milestones and achievements of team members, not just professional accomplishments in pharmaceutical sales.", style: "affiliative" },
    { id: 90, text: "When implementing new policies or procedures, I consider the emotional impact on team members and provide extra support during transitions.", style: "affiliative" },
    { id: 91, text: "I encourage team members to share their feelings and concerns about changes in the pharmaceutical industry or company policies.", style: "affiliative" },
    { id: 92, text: "During recruitment, I prioritize candidates who will fit well with our team culture and contribute to our collaborative pharmaceutical sales environment.", style: "affiliative" },
    { id: 93, text: "I regularly express appreciation and gratitude for my team members' efforts, both in private conversations and public recognition.", style: "affiliative" },
    { id: 94, text: "When team members face ethical dilemmas in pharmaceutical marketing, I provide emotional support while helping them navigate complex situations.", style: "affiliative" },
    { id: 95, text: "I create informal opportunities for team bonding, such as shared meals or casual conversations about life beyond pharmaceutical sales.", style: "affiliative" },
    { id: 96, text: "During crisis situations, I prioritize maintaining team unity and emotional stability while addressing operational challenges.", style: "affiliative" },
    { id: 97, text: "I encourage team members to support each other during difficult periods, fostering a culture of mutual care and assistance.", style: "affiliative" },
    { id: 98, text: "When making tough decisions that affect the team, I consider the emotional impact and provide extra support to help members cope with changes.", style: "affiliative" },
    { id: 99, text: "I believe that strong personal relationships within our pharmaceutical sales team are the foundation for sustained business success.", style: "affiliative" },

    // Democratic Style (33 statements)
    { id: 100, text: "When developing pharmaceutical marketing strategies for the Pakistani market, I actively seek input and ideas from all team members before making decisions.", style: "democratic" },
    { id: 101, text: "I regularly conduct team meetings where medical representatives can vote on important decisions affecting our pharmaceutical sales approach.", style: "democratic" },
    { id: 102, text: "Before implementing new product launch strategies, I facilitate group discussions to gather diverse perspectives from my pharmaceutical sales team.", style: "democratic" },
    { id: 103, text: "When setting territory targets and goals, I involve my team in collaborative planning sessions to ensure buy-in and realistic expectations.", style: "democratic" },
    { id: 104, text: "I encourage open debate and discussion about pharmaceutical industry trends and their impact on our sales strategies in Pakistan.", style: "democratic" },
    { id: 105, text: "During budget planning for promotional activities, I seek input from field representatives about resource allocation and priority setting.", style: "democratic" },
    { id: 106, text: "When facing challenges with regulatory compliance, I facilitate team brainstorming sessions to develop comprehensive solutions together.", style: "democratic" },
    { id: 107, text: "I regularly ask for feedback from my medical representatives about my leadership style and management decisions in pharmaceutical sales.", style: "democratic" },
    { id: 108, text: "Before making changes to sales processes or methodologies, I conduct team consultations to understand potential impacts and gather suggestions.", style: "democratic" },
    { id: 109, text: "When selecting new pharmaceutical products for promotion, I involve my team in evaluation discussions and decision-making processes.", style: "democratic" },
    { id: 110, text: "I create opportunities for team members to participate in strategic planning for our pharmaceutical business in the Pakistani market.", style: "democratic" },
    { id: 111, text: "During performance review periods, I encourage team members to provide input on goal setting and development planning processes.", style: "democratic" },
    { id: 112, text: "When addressing customer complaints or market challenges, I facilitate collaborative problem-solving sessions with my pharmaceutical sales team.", style: "democratic" },
    { id: 113, text: "I regularly seek consensus from my team before implementing new training programs or professional development initiatives.", style: "democratic" },
    { id: 114, text: "When planning medical conferences or educational events, I involve team members in decision-making about content, speakers, and logistics.", style: "democratic" },
    { id: 115, text: "I encourage my pharmaceutical sales team to participate in policy development and procedure refinement for our department.", style: "democratic" },
    { id: 116, text: "Before making territory assignments or role changes, I facilitate discussions with affected team members to understand their preferences and concerns.", style: "democratic" },
    { id: 117, text: "When evaluating new digital tools or CRM systems, I involve my team in the selection process and gather their input on functionality needs.", style: "democratic" },
    { id: 118, text: "I regularly conduct team surveys and feedback sessions to understand satisfaction levels and areas for improvement in our pharmaceutical sales operations.", style: "democratic" },
    { id: 119, text: "During crisis management situations, I facilitate team discussions to develop collaborative responses and action plans.", style: "democratic" },
    { id: 120, text: "When setting team policies or guidelines, I ensure all medical representatives have opportunities to contribute ideas and express concerns.", style: "democratic" },
    { id: 121, text: "I encourage my pharmaceutical sales team to participate in decision-making about resource allocation and priority setting for different therapeutic areas.", style: "democratic" },
    { id: 122, text: "Before implementing new competitive strategies, I facilitate team discussions to gather insights about market conditions and customer needs.", style: "democratic" },
    { id: 123, text: "When planning professional development activities, I involve team members in identifying training needs and selecting appropriate programs.", style: "democratic" },
    { id: 124, text: "I regularly hold open forums where pharmaceutical sales team members can discuss challenges and propose solutions collaboratively.", style: "democratic" },
    { id: 125, text: "When making decisions about promotional campaigns, I seek input from medical representatives about messaging, timing, and target audiences.", style: "democratic" },
    { id: 126, text: "I encourage team participation in developing standard operating procedures and best practices for pharmaceutical sales activities.", style: "democratic" },
    { id: 127, text: "Before implementing organizational changes, I facilitate team discussions to understand potential impacts and gather improvement suggestions.", style: "democratic" },
    { id: 128, text: "When addressing ethical concerns in pharmaceutical marketing, I lead collaborative discussions to develop team consensus on appropriate responses.", style: "democratic" },
    { id: 129, text: "I regularly involve my team in evaluating and improving our customer relationship management processes and strategies.", style: "democratic" },
    { id: 130, text: "When planning team goals and objectives, I facilitate collaborative sessions where all members contribute to target setting and strategy development.", style: "democratic" },
    { id: 131, text: "I encourage my pharmaceutical sales team to participate in decision-making about technology adoption and process improvements.", style: "democratic" },
    { id: 132, text: "Before making significant changes to our pharmaceutical sales approach, I ensure all team members have opportunities to provide input and feedback.", style: "democratic" },

    // Pacesetting Style (33 statements)
    { id: 133, text: "I set extremely high performance standards for pharmaceutical sales and expect my team to match my level of excellence and dedication.", style: "pacesetting" },
    { id: 134, text: "When visiting doctors and key opinion leaders, I demonstrate the exact level of preparation and professionalism I expect from my medical representatives.", style: "pacesetting" },
    { id: 135, text: "I personally achieve the highest sales targets in our pharmaceutical team and expect others to strive for similar outstanding results.", style: "pacesetting" },
    { id: 136, text: "During product presentations, I model the perfect delivery style and expect my team to replicate this level of excellence in their own presentations.", style: "pacesetting" },
    { id: 137, text: "I work longer hours than anyone else in my pharmaceutical sales team and expect similar commitment and dedication from all team members.", style: "pacesetting" },
    { id: 138, text: "When handling complex regulatory requirements, I demonstrate meticulous attention to detail and expect the same precision from my team.", style: "pacesetting" },
    { id: 139, text: "I personally maintain the most comprehensive knowledge of our pharmaceutical products and expect my team to achieve similar expertise levels.", style: "pacesetting" },
    { id: 140, text: "During customer interactions, I demonstrate exceptional relationship-building skills and expect my medical representatives to perform at this same high level.", style: "pacesetting" },
    { id: 141, text: "I set the pace for productivity in our pharmaceutical sales team by consistently exceeding all performance metrics and targets.", style: "pacesetting" },
    { id: 142, text: "When facing challenging market conditions, I demonstrate resilience and high performance, expecting my team to maintain similar standards under pressure.", style: "pacesetting" },
    { id: 143, text: "I personally handle the most difficult key accounts and complex pharmaceutical sales situations, showing my team the level of skill required.", style: "pacesetting" },
    { id: 144, text: "During training sessions, I demonstrate mastery of all pharmaceutical knowledge and expect my team to achieve comparable levels of expertise.", style: "pacesetting" },
    { id: 145, text: "I maintain the highest standards of ethical conduct in pharmaceutical marketing and expect my team to follow my example without compromise.", style: "pacesetting" },
    { id: 146, text: "When implementing new sales strategies, I personally execute them flawlessly first, then expect my team to achieve the same level of implementation.", style: "pacesetting" },
    { id: 147, text: "I demonstrate exceptional time management and organizational skills, expecting my medical representatives to match my efficiency and productivity.", style: "pacesetting" },
    { id: 148, text: "During competitive situations, I personally outperform rival pharmaceutical companies and expect my team to maintain this competitive edge.", style: "pacesetting" },
    { id: 149, text: "I set the standard for continuous learning in our team by constantly updating my pharmaceutical knowledge and expecting others to do the same.", style: "pacesetting" },
    { id: 150, text: "When managing multiple projects simultaneously, I demonstrate perfect execution and expect my team to handle similar complexity with equal success.", style: "pacesetting" },
    { id: 151, text: "I personally achieve the best customer satisfaction scores and expect my pharmaceutical sales team to strive for similar excellence in service delivery.", style: "pacesetting" },
    { id: 152, text: "During crisis management, I demonstrate calm, effective leadership and expect my team to perform with similar composure and effectiveness.", style: "pacesetting" },
    { id: 153, text: "I maintain the most detailed and accurate records of all pharmaceutical sales activities and expect my team to match this level of documentation.", style: "pacesetting" },
    { id: 154, text: "When networking with healthcare professionals, I demonstrate exceptional communication skills and expect my medical representatives to achieve similar rapport.", style: "pacesetting" },
    { id: 155, text: "I personally exceed all quality standards in pharmaceutical marketing activities and expect my team to maintain these same high standards.", style: "pacesetting" },
    { id: 156, text: "During performance periods, I consistently deliver results above expectations and expect my team to strive for similar outstanding achievements.", style: "pacesetting" },
    { id: 157, text: "I demonstrate perfect compliance with all pharmaceutical industry regulations and expect my team to maintain this same level of adherence.", style: "pacesetting" },
    { id: 158, text: "When developing new business opportunities, I personally secure the most challenging accounts and expect my team to pursue similar ambitious targets.", style: "pacesetting" },
    { id: 159, text: "I maintain the highest level of professional development and expect my pharmaceutical sales team to invest equally in their own growth.", style: "pacesetting" },
    { id: 160, text: "During team meetings, I demonstrate thorough preparation and insightful analysis, expecting similar levels of contribution from all members.", style: "pacesetting" },
    { id: 161, text: "I personally handle the most complex pharmaceutical product launches and expect my team to manage their assignments with similar expertise.", style: "pacesetting" },
    { id: 162, text: "When facing obstacles in the Pakistani pharmaceutical market, I demonstrate innovative problem-solving and expect my team to show similar creativity.", style: "pacesetting" },
    { id: 163, text: "I maintain the most comprehensive understanding of competitor activities and expect my medical representatives to achieve similar market intelligence.", style: "pacesetting" },
    { id: 164, text: "During budget management, I demonstrate perfect financial discipline and expect my team to handle resources with the same level of responsibility.", style: "pacesetting" },
    { id: 165, text: "I personally achieve the best work-life integration while maintaining peak performance, expecting my team to strive for similar balance and excellence.", style: "pacesetting" },

    // Coaching Style (35 statements)
    { id: 166, text: "I regularly conduct one-on-one mentoring sessions with my medical representatives to help them develop their pharmaceutical sales skills and career prospects.", style: "coaching" },
    { id: 167, text: "When team members make mistakes in their pharmaceutical marketing activities, I use these as learning opportunities to build their expertise and confidence.", style: "coaching" },
    { id: 168, text: "I invest significant time in understanding each team member's career aspirations and help them develop personalized growth plans in the pharmaceutical industry.", style: "coaching" },
    { id: 169, text: "During doctor visits, I accompany medical representatives to provide real-time feedback and coaching on their presentation and relationship-building skills.", style: "coaching" },
    { id: 170, text: "I help my pharmaceutical sales team members identify their strengths and areas for improvement, providing specific guidance for professional development.", style: "coaching" },
    { id: 171, text: "When introducing new therapeutic areas or products, I focus on building my team's knowledge and confidence through patient, supportive teaching methods.", style: "coaching" },
    { id: 172, text: "I regularly ask my team members about their learning preferences and adapt my coaching style to help them absorb pharmaceutical knowledge more effectively.", style: "coaching" },
    { id: 173, text: "During performance discussions, I focus on helping team members understand how to improve rather than simply evaluating their current pharmaceutical sales results.", style: "coaching" },
    { id: 174, text: "I create stretch assignments and challenging projects that help my medical representatives develop new skills and advance their careers in pharmaceutical sales.", style: "coaching" },
    { id: 175, text: "When team members face difficult customer situations, I guide them through problem-solving processes rather than simply providing solutions.", style: "coaching" },
    { id: 176, text: "I regularly provide constructive feedback to help my pharmaceutical sales team members refine their communication and presentation skills.", style: "coaching" },
    { id: 177, text: "During training sessions, I focus on interactive learning and skill-building rather than just delivering information about pharmaceutical products.", style: "coaching" },
    { id: 178, text: "I help my team members set personal development goals that align with both their career aspirations and our pharmaceutical business objectives.", style: "coaching" },
    { id: 179, text: "When delegating responsibilities, I provide guidance and support to help team members succeed while building their confidence and capabilities.", style: "coaching" },
    { id: 180, text: "I regularly discuss career progression opportunities with my medical representatives and help them prepare for advancement in the pharmaceutical industry.", style: "coaching" },
    { id: 181, text: "During challenging market situations, I help my team develop problem-solving skills and resilience rather than simply directing their actions.", style: "coaching" },
    { id: 182, text: "I encourage my pharmaceutical sales team members to reflect on their experiences and extract learning from both successes and setbacks.", style: "coaching" },
    { id: 183, text: "When team members struggle with specific pharmaceutical knowledge areas, I provide patient, individualized instruction to build their expertise.", style: "coaching" },
    { id: 184, text: "I help my medical representatives understand the connection between their daily activities and their long-term career development in pharmaceutical sales.", style: "coaching" },
    { id: 185, text: "During territory planning, I guide team members through strategic thinking processes to help them develop analytical and planning skills.", style: "coaching" },
    { id: 186, text: "I regularly celebrate my team members' learning achievements and progress, not just their pharmaceutical sales performance results.", style: "coaching" },
    { id: 187, text: "When introducing new technologies or processes, I provide patient, step-by-step guidance to help team members master these tools effectively.", style: "coaching" },
    { id: 188, text: "I help my pharmaceutical sales team members identify and overcome personal barriers that might be limiting their professional growth.", style: "coaching" },
    { id: 189, text: "During customer relationship challenges, I coach my medical representatives on advanced communication and negotiation techniques.", style: "coaching" },
    { id: 190, text: "I regularly share my own learning experiences and mistakes to help my team members avoid similar pitfalls in their pharmaceutical careers.", style: "coaching" },
    { id: 191, text: "When team members show potential for leadership roles, I provide specific mentoring to help them develop management and leadership skills.", style: "coaching" },
    { id: 192, text: "I encourage my pharmaceutical sales team to experiment with new approaches and learn from the results, even when outcomes are not perfect.", style: "coaching" },
    { id: 193, text: "During product knowledge sessions, I use questioning techniques to help team members discover insights rather than simply providing information.", style: "coaching" },
    { id: 194, text: "I help my medical representatives develop self-assessment skills so they can continuously improve their pharmaceutical sales performance independently.", style: "coaching" },
    { id: 195, text: "When team members face ethical dilemmas in pharmaceutical marketing, I guide them through decision-making frameworks rather than simply giving answers.", style: "coaching" },
    { id: 196, text: "I regularly connect my team members with other professionals and learning opportunities to support their development in the pharmaceutical industry.", style: "coaching" },
    { id: 197, text: "During goal-setting sessions, I help team members understand how to create realistic yet challenging objectives for their pharmaceutical sales activities.", style: "coaching" },
    { id: 198, text: "I provide ongoing encouragement and support to help my medical representatives build confidence in handling complex pharmaceutical sales situations.", style: "coaching" },
    { id: 199, text: "When team members express interest in new areas of pharmaceutical business, I help them explore these opportunities and develop relevant skills.", style: "coaching" },
    { id: 200, text: "I focus on building my team's long-term capabilities and career success rather than just achieving short-term pharmaceutical sales targets.", style: "coaching" }
];

// Leadership style descriptions and development tips
const LEADERSHIP_STYLES = {
    coercive: {
        name: "Coercive",
        description: "You lead with a commanding, directive approach. You're decisive and clear about expectations, preferring to maintain control and ensure immediate compliance. This style works well in crisis situations or when quick decisions are needed.",
        tips: [
            "Practice active listening to understand team perspectives before making decisions",
            "Delegate more responsibilities to build team confidence and skills",
            "Provide clear explanations for your decisions to improve team buy-in",
            "Balance directive leadership with opportunities for team input",
            "Focus on developing team members' problem-solving abilities"
        ]
    },
    authoritative: {
        name: "Authoritative",
        description: "You inspire and motivate through a compelling vision. You're excellent at communicating the bigger picture and helping team members understand how their work contributes to meaningful goals. This style builds strong engagement and commitment.",
        tips: [
            "Continue to refine your vision communication skills",
            "Ensure your vision remains relevant and inspiring as markets change",
            "Develop other leadership styles for different situations",
            "Create more opportunities for team members to contribute to vision development",
            "Balance inspiration with practical implementation support"
        ]
    },
    affiliative: {
        name: "Affiliative",
        description: "You prioritize relationships and team harmony. You're skilled at building emotional connections, creating a supportive environment, and helping team members feel valued. This style works well for building team cohesion and managing through difficult times.",
        tips: [
            "Balance relationship focus with performance accountability",
            "Develop skills in giving constructive feedback while maintaining relationships",
            "Learn to make tough decisions when necessary, even if they may strain relationships",
            "Set clear performance expectations alongside emotional support",
            "Practice addressing conflicts directly rather than avoiding them"
        ]
    },
    democratic: {
        name: "Democratic",
        description: "You value collaboration and seek input from team members in decision-making. You're skilled at facilitating discussions, building consensus, and ensuring everyone has a voice. This style works well when team expertise is high and buy-in is crucial.",
        tips: [
            "Learn when to make quick decisions without extensive consultation",
            "Develop skills in managing disagreement and reaching decisions when consensus isn't possible",
            "Balance participation with efficiency in decision-making processes",
            "Strengthen your ability to synthesize diverse viewpoints into clear direction",
            "Practice making unpopular decisions when necessary for business success"
        ]
    },
    pacesetting: {
        name: "Pacesetting",
        description: "You lead by example, setting high standards and demonstrating excellence. You're driven, results-oriented, and expect team members to match your level of performance. This style works well with highly motivated, skilled team members.",
        tips: [
            "Develop patience for team members who may need more time to reach your standards",
            "Practice providing clear guidance rather than expecting others to figure things out",
            "Balance high expectations with supportive coaching and development",
            "Learn to delegate effectively without micromanaging",
            "Develop skills in motivating team members who may not be naturally self-driven"
        ]
    },
    coaching: {
        name: "Coaching",
        description: "You focus on developing team members' long-term capabilities and career growth. You're skilled at providing guidance, feedback, and learning opportunities. This style builds strong individual performance and team capability over time.",
        tips: [
            "Continue to develop your coaching and mentoring skills",
            "Balance development focus with achieving short-term business results",
            "Learn to adapt your coaching style to different personality types and learning preferences",
            "Develop skills in performance management when coaching isn't sufficient",
            "Create systems to track and measure development progress effectively"
        ]
    }
};